declare function AutoCalc(): void;
declare function CalcStatusPoint(flag: boolean): void;
declare function OnClickSkillSWLearned(): void;
declare function OnClickSlotModeButton(): void;
declare function OnClickUrlOutMIG(): void;
declare function StAllCalc(): void;
declare function changeJobSettings(jobId: string): void;
declare function generateImage(): void;
declare function hideLoadingIndicator(): void;
declare function html2canvas(a: any, b: any): Promise<HTMLCanvasElement>;
declare function showLoadingIndicator(): void;
declare let CardObjNew: Array<Array<string | number>>;
declare let ItemObjNew: Array<Array<string | number>>;
