
//----------------------------------------------------------------
// データの要素番号
//----------------------------------------------------------------
CGlobalConstManager.DefineEnum(
	"EnumSkillDataIndex",
	[
		"SKILL_DATA_INDEX_ID",
		"SKILL_DATA_INDEX_MAXLV",
		"SKILL_DATA_INDEX_NAME",
		"SKILL_DATA_INDEX_REFID",
	],
	0,
	1
);



// TODO: 整理予定
SKILL_LEVEL_VALUE_SEIMEINO_TAMASHI_KOKA_NOKORI_HP_OVER_100 = 4;
SKILL_LEVEL_VALUE_SEIMEINO_TAMASHI_KOKA_NOKORI_HP_OVER_81 = 3;
SKILL_LEVEL_VALUE_SEIMEINO_TAMASHI_KOKA_NOKORI_HP_OVER_51 = 2;
SKILL_LEVEL_VALUE_SEIMEINO_TAMASHI_KOKA_NOKORI_HP_OVER_10 = 1;
SKILL_LEVEL_VALUE_SEIMEINO_TAMASHI_KOKA_NOKORI_HP_OVER_0 = 0;
