version: 2.1

executors:
  self-hosted-executor:
    machine: true  # self-hosted runnerの場合、machine: true を指定
    resource_class: m10i/aws  # self-hosted runnerの名前を指定

# Job を定義
jobs:
  e2e-test:
    executor: self-hosted-executor  # self-hosted executorを使用
    steps:
      # 1. GitHubのホストキーをknown_hostsに追加（SSHエラー対策）
      - run:
          name: Add GitHub to known_hosts
          command: |
            mkdir -p ~/.ssh
            grep "github\.com" ~/.ssh/known_hosts >/dev/null || ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      # 2. 指定した場所にcheckout
      - checkout:
          path: /var/www/html/roratorio-hub  # チェックアウト先を指定

      # 3. Gitの安全ディレクトリを設定（エラー対策）
      - run:
          name: Set Git Safe Directory
          command: |
            git config --global --add safe.directory /var/www/html/roratorio-hub

      # 4. 指定した場所でgit pullを実行
      - run:
          name: Git Pull in Specified Directory
          command: |
            cd /var/www/html/roratorio-hub
            git fetch origin ${CIRCLE_BRANCH}
            git reset --hard origin/${CIRCLE_BRANCH}  # 現在のbranchをリモートに強制的に合わせる（必要に応じて調整）

      # 5. 環境クリーンアップ用のシェルを実行
      - run:
          name: Run Shell Script
          command: |
            cd /var/www/html/roratorio-hub/workspace
            bash ./clean.sh

      # 6. Playwrightコンテナを起動し、テストを実行（結果を直接受け取る）
      - run:
          name: Run Playwright Tests in Container
          command: |
            cd /var/www/html/roratorio-hub
            podman pull public.ecr.aws/u3l2i4k1/m10i/roratorio-hub-e2e-testkit:latest-arm64
            mkdir -p test-results
            podman run --rm --replace \
              --name testing-roratorio-hub \
              --network host \
              -v $(pwd)/test-results:/opt/workspace/test-results \
              -e BASE_URL="http://localhost/roratorio-hub/ro4/m/calcx.html" \
              public.ecr.aws/u3l2i4k1/m10i/roratorio-hub-e2e-testkit:latest-arm64 \
              npx playwright test --output=/opt/workspace/test-results

      # 7. テスト結果をartifactsとして保存
      - store_artifacts:
          path: /var/www/html/roratorio-hub/test-results
          destination: test-results

# Workflows を定義（pushイベントでジョブを実行）
workflows:
  tests:
    jobs:
      - e2e-test:
          filters:
            branches:
              only: /^(feature\/.*|hotfix\/.*|patch\/.*)$/  # feature/*, hotfix/*, patch/* のブランチで実行
