/**
 * EnumBattleDataIndex の定数定義.
 *
 * このファイルが値の一次情報。直接編集してよい（旧・自動生成方式は廃止）。
 *
 * **既存の定数値を変えるとセーブデータとアイテムデータの解釈が壊れる。**
 * 追加は末尾に足すこと（途中への挿入は後続の値をずらす）。
 * 区切りコメント（列挙定数 / 疑似定数）は検証が種別判定に使うため残すこと。
 * コンテナ併設ファイルでは createEnum の引数にも同じ定数名を追加する。
 *
 * 変更したら node util/enum/verify-enum-values.mjs を通すこと。
 */
import { createEnum } from './createEnum.js';

// ---- 列挙定数 ----
export const BATTLE_DATA_INDEX_ACTIVE_SKILL                    = 0;
export const BATTLE_DATA_INDEX_ATTACK_ELEMENT                  = 1;
export const BATTLE_DATA_INDEX_RANGE_FLAG                      = 2;
export const BATTLE_DATA_INDEX_STRDEX_BONUS                    = 3;
export const BATTLE_DATA_INDEX_STRDEX_PENARTY                  = 4;
export const BATTLE_DATA_INDEX_SIZE_MODIFY                     = 5;
export const BATTLE_DATA_INDEX_HIT_RATE                        = 6;
export const BATTLE_DATA_INDEX_HIT_RATE_AUTO_SPELL             = 7;
export const BATTLE_DATA_INDEX_HIT_RATE_DISP                   = 8;
export const BATTLE_DATA_INDEX_CRITICAL_RATE                   = 9;
export const BATTLE_DATA_INDEX_AVOID_RATE                      = 10;
export const BATTLE_DATA_INDEX_BASE_DAMAGE_MIN                 = 11;
export const BATTLE_DATA_INDEX_BASE_DAMAGE_AVE                 = 12;
export const BATTLE_DATA_INDEX_BASE_DAMAGE_MAX                 = 13;
export const BATTLE_DATA_INDEX_BASE_DAMAGE_MIN_GX              = 14;
export const BATTLE_DATA_INDEX_BASE_DAMAGE_AVE_GX              = 15;
export const BATTLE_DATA_INDEX_BASE_DAMAGE_MAX_GX              = 16;
export const BATTLE_DATA_INDEX_BASE_DAMAGE_MIN_QUAKE           = 17;
export const BATTLE_DATA_INDEX_BASE_DAMAGE_AVE_QUAKE           = 18;
export const BATTLE_DATA_INDEX_BASE_DAMAGE_MAX_QUAKE           = 19;
export const BATTLE_DATA_INDEX_CRITICAL_ATK_MIN                = 20;
export const BATTLE_DATA_INDEX_CRITICAL_ATK_AVE                = 21;
export const BATTLE_DATA_INDEX_CRITICAL_ATK_MAX                = 22;
export const BATTLE_DATA_INDEX_ARMS_ATK_MIN                    = 23;
export const BATTLE_DATA_INDEX_ARMS_ATK_AVE                    = 24;
export const BATTLE_DATA_INDEX_ARMS_ATK_MAX                    = 25;
export const BATTLE_DATA_INDEX_HAND_ATK_PSYCO_FIX              = 26;
export const BATTLE_DATA_INDEX_HAND_ATK                        = 27;
export const BATTLE_DATA_INDEX_GUIDED_DAMAGE                   = 28;
export const BATTLE_DATA_INDEX_ATTACK_COUNT_MIN                = 29;
export const BATTLE_DATA_INDEX_ATTACK_COUNT_AVE                = 30;
export const BATTLE_DATA_INDEX_ATTACK_COUNT_MAX                = 31;
export const BATTLE_DATA_INDEX_DAMAGE_PER_SECOND               = 32;
export const BATTLE_DATA_INDEX_FINAL_DAMAGE_MIN                = 33;
export const BATTLE_DATA_INDEX_FINAL_DAMAGE_AVE                = 34;
export const BATTLE_DATA_INDEX_FINAL_DAMAGE_MAX                = 35;
export const BATTLE_DATA_INDEX_RECEIVE_DAMAGE_MIN              = 36;
export const BATTLE_DATA_INDEX_RECEIVE_DAMAGE_AVE              = 37;
export const BATTLE_DATA_INDEX_RECEIVE_DAMAGE_MAX              = 38;
export const BATTLE_DATA_INDEX_REFLECT_DAMAGE_MIN_RS           = 39;
export const BATTLE_DATA_INDEX_REFLECT_DAMAGE_AVE_RS           = 40;
export const BATTLE_DATA_INDEX_REFLECT_DAMAGE_MAX_RS           = 41;
export const BATTLE_DATA_INDEX_REFLECT_DAMAGE_MIN_SPEC         = 42;
export const BATTLE_DATA_INDEX_REFLECT_DAMAGE_AVE_SPEC         = 43;
export const BATTLE_DATA_INDEX_REFLECT_DAMAGE_MAX_SPEC         = 44;
export const BATTLE_DATA_INDEX_REFLECT_DAMAGE_MIN_SHIELD_SPELL = 45;
export const BATTLE_DATA_INDEX_REFLECT_DAMAGE_AVE_SHIELD_SPELL = 46;
export const BATTLE_DATA_INDEX_REFLECT_DAMAGE_MAX_SHIELD_SPELL = 47;
export const BATTLE_DATA_INDEX_RECEIVE_DAMAGE_AVOIDS           = 48;

/** 列挙型コンテナ（Count / For / GetDefinedName / GetDefinedValue）。 */
export const EnumBattleDataIndex = createEnum('EnumBattleDataIndex', {
    BATTLE_DATA_INDEX_ACTIVE_SKILL,
    BATTLE_DATA_INDEX_ATTACK_ELEMENT,
    BATTLE_DATA_INDEX_RANGE_FLAG,
    BATTLE_DATA_INDEX_STRDEX_BONUS,
    BATTLE_DATA_INDEX_STRDEX_PENARTY,
    BATTLE_DATA_INDEX_SIZE_MODIFY,
    BATTLE_DATA_INDEX_HIT_RATE,
    BATTLE_DATA_INDEX_HIT_RATE_AUTO_SPELL,
    BATTLE_DATA_INDEX_HIT_RATE_DISP,
    BATTLE_DATA_INDEX_CRITICAL_RATE,
    BATTLE_DATA_INDEX_AVOID_RATE,
    BATTLE_DATA_INDEX_BASE_DAMAGE_MIN,
    BATTLE_DATA_INDEX_BASE_DAMAGE_AVE,
    BATTLE_DATA_INDEX_BASE_DAMAGE_MAX,
    BATTLE_DATA_INDEX_BASE_DAMAGE_MIN_GX,
    BATTLE_DATA_INDEX_BASE_DAMAGE_AVE_GX,
    BATTLE_DATA_INDEX_BASE_DAMAGE_MAX_GX,
    BATTLE_DATA_INDEX_BASE_DAMAGE_MIN_QUAKE,
    BATTLE_DATA_INDEX_BASE_DAMAGE_AVE_QUAKE,
    BATTLE_DATA_INDEX_BASE_DAMAGE_MAX_QUAKE,
    BATTLE_DATA_INDEX_CRITICAL_ATK_MIN,
    BATTLE_DATA_INDEX_CRITICAL_ATK_AVE,
    BATTLE_DATA_INDEX_CRITICAL_ATK_MAX,
    BATTLE_DATA_INDEX_ARMS_ATK_MIN,
    BATTLE_DATA_INDEX_ARMS_ATK_AVE,
    BATTLE_DATA_INDEX_ARMS_ATK_MAX,
    BATTLE_DATA_INDEX_HAND_ATK_PSYCO_FIX,
    BATTLE_DATA_INDEX_HAND_ATK,
    BATTLE_DATA_INDEX_GUIDED_DAMAGE,
    BATTLE_DATA_INDEX_ATTACK_COUNT_MIN,
    BATTLE_DATA_INDEX_ATTACK_COUNT_AVE,
    BATTLE_DATA_INDEX_ATTACK_COUNT_MAX,
    BATTLE_DATA_INDEX_DAMAGE_PER_SECOND,
    BATTLE_DATA_INDEX_FINAL_DAMAGE_MIN,
    BATTLE_DATA_INDEX_FINAL_DAMAGE_AVE,
    BATTLE_DATA_INDEX_FINAL_DAMAGE_MAX,
    BATTLE_DATA_INDEX_RECEIVE_DAMAGE_MIN,
    BATTLE_DATA_INDEX_RECEIVE_DAMAGE_AVE,
    BATTLE_DATA_INDEX_RECEIVE_DAMAGE_MAX,
    BATTLE_DATA_INDEX_REFLECT_DAMAGE_MIN_RS,
    BATTLE_DATA_INDEX_REFLECT_DAMAGE_AVE_RS,
    BATTLE_DATA_INDEX_REFLECT_DAMAGE_MAX_RS,
    BATTLE_DATA_INDEX_REFLECT_DAMAGE_MIN_SPEC,
    BATTLE_DATA_INDEX_REFLECT_DAMAGE_AVE_SPEC,
    BATTLE_DATA_INDEX_REFLECT_DAMAGE_MAX_SPEC,
    BATTLE_DATA_INDEX_REFLECT_DAMAGE_MIN_SHIELD_SPELL,
    BATTLE_DATA_INDEX_REFLECT_DAMAGE_AVE_SHIELD_SPELL,
    BATTLE_DATA_INDEX_REFLECT_DAMAGE_MAX_SHIELD_SPELL,
    BATTLE_DATA_INDEX_RECEIVE_DAMAGE_AVOIDS,
}, {
});
