/**
 * EnumMigRequiredJobSeriesIdReincaneted の定数定義.
 *
 * このファイルが値の一次情報。直接編集してよい（旧・自動生成方式は廃止）。
 *
 * **既存の定数値を変えるとセーブデータとアイテムデータの解釈が壊れる。**
 * 追加は末尾に足すこと（途中への挿入は後続の値をずらす）。
 * 区切りコメント（列挙定数 / 疑似定数）は検証が種別判定に使うため残すこと。
 * コンテナ併設ファイルでは createEnum の引数にも同じ定数名を追加する。
 *
 * 変更したら node util/enum/verify-enum-values.mjs を通すこと。
 */

// ---- 列挙定数 ----
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_NOVICE           = 0;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_SWORDMAN         = 1;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_THIEF            = 2;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_ACOLYTE          = 3;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_ARCHER           = 4;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_MAGICIAN         = 5;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_MARCHANT         = 6;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_KNIGHT           = 7;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_ASSASIN          = 8;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_PRIEST           = 9;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_HUNTER           = 10;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_WIZARD           = 11;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_BLACKSMITH       = 12;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_CRUSADER         = 13;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_ROGUE            = 14;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_MONK             = 15;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_BARD             = 16;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_DANCER           = 17;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_SAGE             = 18;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_ALCHEMIST        = 19;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_SUPERNOVICE      = 20;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_LORDKNIGHT       = 21;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_ASSASINCROSS     = 22;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_HIGHPRIEST       = 23;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_SNIPER           = 24;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_HIGHWIZARD       = 25;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_WHITESMITH       = 26;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_PALADIN          = 27;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_CHASER           = 28;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_CHAMPION         = 29;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_CROWN            = 30;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_ZYPSY            = 31;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_PROFESSOR        = 32;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_CREATOR          = 33;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_HI_NOVICE        = 34;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_HI_SWORDMAN      = 35;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_HI_THIEF         = 36;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_HI_ACOLYTE       = 37;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_HI_ARCHER        = 38;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_HI_MAGICIAN      = 39;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_HI_MARCHANT      = 40;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_TAEGWON          = 41;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_STARGRADIATOR    = 42;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_SOULLINKER       = 43;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_NINJA            = 44;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_GUNSLINGER       = 45;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_RUNEKNIGHT       = 46;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_GILOTINCROSS     = 47;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_ARCBISHOP        = 48;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_RANGER           = 49;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_WARLOCK          = 50;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_MECHANIC         = 51;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_ROYALGUARD       = 52;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_SHADOWCHASER     = 53;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_SHURA            = 54;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_MINSTREL         = 55;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_WANDERER         = 56;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_SORCERER         = 57;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_GENETIC          = 58;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_KAGERO           = 59;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_OBORO            = 60;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_SUPERNOVICE_PLUS = 61;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_REBELLION        = 62;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_SUMMONER         = 63;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_STAR_EMPEROR     = 64;
export const MIG_REQUIRED_JOB_SERIES_REINCANATED_ID_SOUL_REAPER      = 65;
