/**
 * EnumMigJobSeriesId の定数定義.
 *
 * このファイルが値の一次情報。直接編集してよい（旧・自動生成方式は廃止）。
 *
 * **既存の定数値を変えるとセーブデータとアイテムデータの解釈が壊れる。**
 * 追加は末尾に足すこと（途中への挿入は後続の値をずらす）。
 * 区切りコメント（列挙定数 / 疑似定数）は検証が種別判定に使うため残すこと。
 * コンテナ併設ファイルでは createEnum の引数にも同じ定数名を追加する。
 *
 * 変更したら node util/enum/verify-enum-values.mjs を通すこと。
 */

// ---- 列挙定数 ----
export const MIG_JOB_SERIES_ID_NOVICE                  = 0;
export const MIG_JOB_SERIES_ID_NOVICE_SERIES           = 1;
export const MIG_JOB_SERIES_ID_SWORDMAN                = 2;
export const MIG_JOB_SERIES_ID_SWORDMAN_SERIES         = 3;
export const MIG_JOB_SERIES_ID_THIEF                   = 4;
export const MIG_JOB_SERIES_ID_THIEF_SERIES            = 5;
export const MIG_JOB_SERIES_ID_ACOLYTE                 = 6;
export const MIG_JOB_SERIES_ID_ACOLYTE_SERIES          = 7;
export const MIG_JOB_SERIES_ID_ARCHER                  = 8;
export const MIG_JOB_SERIES_ID_ARCHER_SERIES           = 9;
export const MIG_JOB_SERIES_ID_MAGICIAN                = 10;
export const MIG_JOB_SERIES_ID_MAGICIAN_SERIES         = 11;
export const MIG_JOB_SERIES_ID_MARCHANT                = 12;
export const MIG_JOB_SERIES_ID_MARCHANT_SERIES         = 13;
export const MIG_JOB_SERIES_ID_KNIGHT                  = 14;
export const MIG_JOB_SERIES_ID_KNIGHT_SERIES           = 15;
export const MIG_JOB_SERIES_ID_ASSASIN                 = 16;
export const MIG_JOB_SERIES_ID_ASSASIN_SERIES          = 17;
export const MIG_JOB_SERIES_ID_PRIEST                  = 18;
export const MIG_JOB_SERIES_ID_PRIEST_SERIES           = 19;
export const MIG_JOB_SERIES_ID_HUNTER                  = 20;
export const MIG_JOB_SERIES_ID_HUNTER_SERIES           = 21;
export const MIG_JOB_SERIES_ID_WIZARD                  = 22;
export const MIG_JOB_SERIES_ID_WIZARD_SERIES           = 23;
export const MIG_JOB_SERIES_ID_BLACKSMITH              = 24;
export const MIG_JOB_SERIES_ID_BLACKSMITH_SERIES       = 25;
export const MIG_JOB_SERIES_ID_CRUSADER                = 26;
export const MIG_JOB_SERIES_ID_CRUSADER_SERIES         = 27;
export const MIG_JOB_SERIES_ID_ROGUE                   = 28;
export const MIG_JOB_SERIES_ID_ROGUE_SERIES            = 29;
export const MIG_JOB_SERIES_ID_MONK                    = 30;
export const MIG_JOB_SERIES_ID_MONK_SERIES             = 31;
export const MIG_JOB_SERIES_ID_BARD                    = 32;
export const MIG_JOB_SERIES_ID_BARD_SERIES             = 33;
export const MIG_JOB_SERIES_ID_DANCER                  = 34;
export const MIG_JOB_SERIES_ID_DANCER_SERIES           = 35;
export const MIG_JOB_SERIES_ID_SAGE                    = 36;
export const MIG_JOB_SERIES_ID_SAGE_SERIES             = 37;
export const MIG_JOB_SERIES_ID_ALCHEMIST               = 38;
export const MIG_JOB_SERIES_ID_ALCHEMIST_SERIES        = 39;
export const MIG_JOB_SERIES_ID_SUPERNOVICE             = 40;
export const MIG_JOB_SERIES_ID_SUPERNOVICE_SERIES      = 41;
export const MIG_JOB_SERIES_ID_LORDKNIGHT              = 42;
export const MIG_JOB_SERIES_ID_LORDKNIGHT_SERIES       = 43;
export const MIG_JOB_SERIES_ID_ASSASINCROSS            = 44;
export const MIG_JOB_SERIES_ID_ASSASINCROSS_SERIES     = 45;
export const MIG_JOB_SERIES_ID_HIGHPRIEST              = 46;
export const MIG_JOB_SERIES_ID_HIGHPRIEST_SERIES       = 47;
export const MIG_JOB_SERIES_ID_SNIPER                  = 48;
export const MIG_JOB_SERIES_ID_SNIPER_SERIES           = 49;
export const MIG_JOB_SERIES_ID_HIGHWIZARD              = 50;
export const MIG_JOB_SERIES_ID_HIGHWIZARD_SERIES       = 51;
export const MIG_JOB_SERIES_ID_WHITESMITH              = 52;
export const MIG_JOB_SERIES_ID_WHITESMITH_SERIES       = 53;
export const MIG_JOB_SERIES_ID_PALADIN                 = 54;
export const MIG_JOB_SERIES_ID_PALADIN_SERIES          = 55;
export const MIG_JOB_SERIES_ID_CHASER                  = 56;
export const MIG_JOB_SERIES_ID_CHASER_SERIES           = 57;
export const MIG_JOB_SERIES_ID_CHAMPION                = 58;
export const MIG_JOB_SERIES_ID_CHAMPION_SERIES         = 59;
export const MIG_JOB_SERIES_ID_CROWN                   = 60;
export const MIG_JOB_SERIES_ID_CROWN_SERIES            = 61;
export const MIG_JOB_SERIES_ID_ZYPSY                   = 62;
export const MIG_JOB_SERIES_ID_ZYPSY_SERIES            = 63;
export const MIG_JOB_SERIES_ID_PROFESSOR               = 64;
export const MIG_JOB_SERIES_ID_PROFESSOR_SERIES        = 65;
export const MIG_JOB_SERIES_ID_CREATOR                 = 66;
export const MIG_JOB_SERIES_ID_CREATOR_SERIES          = 67;
export const MIG_JOB_SERIES_ID_HI_NOVICE               = 68;
export const MIG_JOB_SERIES_ID_HI_NOVICE_SERIES        = 69;
export const MIG_JOB_SERIES_ID_HI_SWORDMAN             = 70;
export const MIG_JOB_SERIES_ID_HI_SWORDMAN_SERIES      = 71;
export const MIG_JOB_SERIES_ID_HI_THIEF                = 72;
export const MIG_JOB_SERIES_ID_HI_THIEF_SERIES         = 73;
export const MIG_JOB_SERIES_ID_HI_ACOLYTE              = 74;
export const MIG_JOB_SERIES_ID_HI_ACOLYTE_SERIES       = 75;
export const MIG_JOB_SERIES_ID_HI_ARCHER               = 76;
export const MIG_JOB_SERIES_ID_HI_ARCHER_SERIES        = 77;
export const MIG_JOB_SERIES_ID_HI_MAGICIAN             = 78;
export const MIG_JOB_SERIES_ID_HI_MAGICIAN_SERIES      = 79;
export const MIG_JOB_SERIES_ID_HI_MARCHANT             = 80;
export const MIG_JOB_SERIES_ID_HI_MARCHANT_SERIES      = 81;
export const MIG_JOB_SERIES_ID_TAEGWON                 = 82;
export const MIG_JOB_SERIES_ID_TAEGWON_SERIES          = 83;
export const MIG_JOB_SERIES_ID_STARGRADIATOR           = 84;
export const MIG_JOB_SERIES_ID_STARGRADIATOR_SERIES    = 85;
export const MIG_JOB_SERIES_ID_SOULLINKER              = 86;
export const MIG_JOB_SERIES_ID_SOULLINKER_SERIES       = 87;
export const MIG_JOB_SERIES_ID_NINJA                   = 88;
export const MIG_JOB_SERIES_ID_NINJA_SERIES            = 89;
export const MIG_JOB_SERIES_ID_GUNSLINGER              = 90;
export const MIG_JOB_SERIES_ID_GUNSLINGER_SERIES       = 91;
export const MIG_JOB_SERIES_ID_RUNEKNIGHT              = 92;
export const MIG_JOB_SERIES_ID_RUNEKNIGHT_SERIES       = 93;
export const MIG_JOB_SERIES_ID_GILOTINCROSS            = 94;
export const MIG_JOB_SERIES_ID_GILOTINCROSS_SERIES     = 95;
export const MIG_JOB_SERIES_ID_ARCBISHOP               = 96;
export const MIG_JOB_SERIES_ID_ARCBISHOP_SERIES        = 97;
export const MIG_JOB_SERIES_ID_RANGER                  = 98;
export const MIG_JOB_SERIES_ID_RANGER_SERIES           = 99;
export const MIG_JOB_SERIES_ID_WARLOCK                 = 100;
export const MIG_JOB_SERIES_ID_WARLOCK_SERIES          = 101;
export const MIG_JOB_SERIES_ID_MECHANIC                = 102;
export const MIG_JOB_SERIES_ID_MECHANIC_SERIES         = 103;
export const MIG_JOB_SERIES_ID_ROYALGUARD              = 104;
export const MIG_JOB_SERIES_ID_ROYALGUARD_SERIES       = 105;
export const MIG_JOB_SERIES_ID_SHADOWCHASER            = 106;
export const MIG_JOB_SERIES_ID_SHADOWCHASER_SERIES     = 107;
export const MIG_JOB_SERIES_ID_SHURA                   = 108;
export const MIG_JOB_SERIES_ID_SHURA_SERIES            = 109;
export const MIG_JOB_SERIES_ID_MINSTREL                = 110;
export const MIG_JOB_SERIES_ID_MINSTREL_SERIES         = 111;
export const MIG_JOB_SERIES_ID_WANDERER                = 112;
export const MIG_JOB_SERIES_ID_WANDERER_SERIES         = 113;
export const MIG_JOB_SERIES_ID_SORCERER                = 114;
export const MIG_JOB_SERIES_ID_SORCERER_SERIES         = 115;
export const MIG_JOB_SERIES_ID_GENETIC                 = 116;
export const MIG_JOB_SERIES_ID_GENETIC_SERIES          = 117;
export const MIG_JOB_SERIES_ID_KAGERO                  = 118;
export const MIG_JOB_SERIES_ID_KAGERO_SERIES           = 119;
export const MIG_JOB_SERIES_ID_OBORO                   = 120;
export const MIG_JOB_SERIES_ID_OBORO_SERIES            = 121;
export const MIG_JOB_SERIES_ID_SUPERNOVICE_PLUS        = 122;
export const MIG_JOB_SERIES_ID_SUPERNOVICE_PLUS_SERIES = 123;
export const MIG_JOB_SERIES_ID_REBELLION               = 124;
export const MIG_JOB_SERIES_ID_REBELLION_SERIES        = 125;
export const MIG_JOB_SERIES_ID_SUMMONER                = 126;
export const MIG_JOB_SERIES_ID_SUMMONER_SERIES         = 127;
export const MIG_JOB_SERIES_ID_STAR_EMPEROR            = 128;
export const MIG_JOB_SERIES_ID_STAR_EMPEROR_SERIES     = 129;
export const MIG_JOB_SERIES_ID_SOUL_REAPER             = 130;
export const MIG_JOB_SERIES_ID_SOUL_REAPER_SERIES      = 131;

// ---- 疑似定数（旧 DefinePseudoEnum） ----
export const MIG_JOB_SERIES_ID_COUNT                   = 132;
export const MIG_JOB_SERIES_ID_ANY                     = 133;
export const MIG_JOB_SERIES_ID_ALL                     = 134;
