import {
    AUTO_SPELL_TRIGGER_ANY_ATTACK, AUTO_SPELL_TRIGGER_ANY_DAMAGED, AUTO_SPELL_TRIGGER_LONGRANGE_ATTACK, AUTO_SPELL_TRIGGER_LONGRANGE_DAMAGED, AUTO_SPELL_TRIGGER_MAGICAL_ATTACK, AUTO_SPELL_TRIGGER_MAGICAL_DAMAGED,
    AUTO_SPELL_TRIGGER_PHYSICAL_ATTACK, AUTO_SPELL_TRIGGER_PHYSICAL_DAMAGED, AUTO_SPELL_TRIGGER_SHORTRANGE_ATTACK, AUTO_SPELL_TRIGGER_SHORTRANGE_DAMAGED, AUTO_SPELL_TRIGGER_UNKNOWN,
} from "../const/EnumAutoSpellTrigger.js";

export const AUTO_SPELL_ID_CUSTOM_BIAS = 20000;


/**
 * オートスペル発動トリガのテキストを取得する.
 * @param triggerId 発動トリガＩＤ
 */
export function GetAutoSpellTriggerText(triggerId) {
	switch (triggerId) {
	case AUTO_SPELL_TRIGGER_UNKNOWN:
		return "特定条件の時";

	case AUTO_SPELL_TRIGGER_PHYSICAL_ATTACK:
		return "物理攻撃時";

	case AUTO_SPELL_TRIGGER_SHORTRANGE_ATTACK:
		return "近接攻撃時";

	case AUTO_SPELL_TRIGGER_LONGRANGE_ATTACK:
		return "遠距離攻撃時";

	case AUTO_SPELL_TRIGGER_ANY_ATTACK:
		return "物理・魔法攻撃時";

	case AUTO_SPELL_TRIGGER_MAGICAL_ATTACK:
		return "魔法攻撃時";

	case AUTO_SPELL_TRIGGER_PHYSICAL_DAMAGED:
		return "物理攻撃を受けた時";

	case AUTO_SPELL_TRIGGER_SHORTRANGE_DAMAGED:
		return "近距離物理攻撃を受けた時";

	case AUTO_SPELL_TRIGGER_LONGRANGE_DAMAGED:
		return "遠距離物理攻撃を受けた時";

	case AUTO_SPELL_TRIGGER_MAGICAL_DAMAGED:
		return "魔法攻撃を受けた時";

	case AUTO_SPELL_TRIGGER_ANY_DAMAGED:
		return "物理または魔法攻撃を受けた時";

	}

	return "不明";
}


