if (_DATA_CREATE_MODE) {		// _DATA_CREATE_MODE



(function () {



	// ID定数登録
	g_constDataManager.enchListDataManager.RegisterId("MIG_ENCH_LIST_ID_NONE", 0);



	// ID定数登録
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_NONE", 0)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_YA", 1)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_TETSUNO_YA", 2)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_KOTETSUNO_YA", 3)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_ORIDEOKONNO_YA", 4)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_KARYUDONO_YA", 5)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_ELFNO_YA", 6)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_SUISHONO_YA", 7)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_GANSEKINO_YA", 8)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_HONOONO_YA", 9)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_KAZENO_YA", 10)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_SABITA_YA", 11)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_GINNO_YA", 12)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_HAMAYA", 13)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_SEINARU_YA", 14)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_KAGEYA", 15)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_MUKEINO_YA", 16)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_SURUDOI_YA", 18)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_CURSE_ARROW", 19)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_SILENCE_ARROW", 20)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_SLEEP_ARROW", 21)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_FLASH_ARROW", 22)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_KORINO_YA", 23)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_DOKUYA", 24)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_BULLET", 26)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_BLOOD_BULLET_C", 27)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_AP_BULLET", 28)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_ICE_BULLET", 29)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_FREEZING_BULLET", 30)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_MAGICAL_STONE_BULLET", 31)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_FLARE_BULLET", 32)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_BLAZE_BULLET", 33)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_LIGHTNING_BULLET", 34)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_ELECTRIC_BULLET", 35)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_POISON_BULLET", 36)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_SILVER_BULLET_C", 37)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_SUNCTFIED_BULLET", 38)
	g_constDataManager.arrowDataManager.RegisterId("MIG_ARROW_ID_BLIND_BULLET", 39)



	// ID定数登録
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_CARGA_MACE", 1326);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ELVEN_BOW", 1327);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_DULLGER", 1328);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_LAFINE_STUFF", 1329);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_HYUKKENO_FUKU", 2170);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_LAFINE_SHIELD", 2322);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ARASHINO_YUMI", 2376);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_CARDYUINO_MIMI", 2499);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_CARDYUINO_HOI", 2667);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SCARABA_HIGHHEEL", 3284);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GOYUMUSONO_MONBOSHI", 3431);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GOYUMUSONO_TSURANUKI", 3976);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_BOINO_MUFFLER", 4007);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILUSION_SHIELD_1", 4010);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GOYUMUSONO_KACCHU", 4106);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_WANDER_EGG_BASKET", 4235);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_GLORY", 4239);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_CRYSTAL_BLADE_NECKLACE", 4240);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_OSHARENA_SILENT_SHOES", 4242);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_TWIN_BLAZE", 4243);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_EIKONO_MIHATA_AO", 4244);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAITEI_SHINDENNO_ZAIHO", 4245);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_POWERED_WING", 4247);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_FUSHICHONO_RING", 4248);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KUCHITA_GARDEN_KNIFE", 4251);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SHITSUBONO_SHINENTAI_SHOES", 4253);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_BOSONO_SHINENTAI_SHOES", 4259);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ERYMANTHNO_KAWA", 4264);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ANULUS_IRA", 4265);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_ANIMAL_ROBE", 4267);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_ANIMAL_ROBE", 4268);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_ANIMAL_ROBE", 4269);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_GATLING_SUIT", 4270);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_GATLING_SUIT", 4271);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_GATLING_SUIT", 4272);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_CRUCIFORM_SUIT", 4273);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_CRUCIFORM_SUIT", 4274);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_CRUCIFORM_SUIT", 4275);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_AZATOI_KEROKERO_KAPPA", 4276);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_PARADISE_LOST", 4277);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ZYASPER_RING", 4278);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_FURUBITA_WHITE_LILIUM_ROBE", 4280);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_WHITE_LILIUM_ROBE", 4281);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_WHITE_LILIUM_ROBE", 4283);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_TAIKYOKUNO_MIMIKAZARI_KIIRO", 4285);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SUHAINO_YUBIWA", 4286);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GLOTONERIA", 4288);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILUSION_SHIELD_2", 4289);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_AUTOMATIC_SHIELD_1", 4296);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_AUTOMATIC_SHIELD_2", 4297);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ALPHA_CORE", 4298);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GUARDIAN_KNIGHTS_CRYMORE", 4300);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GUARDIAN_KNIGHTS_SPEAR", 4301);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GUARDIAN_KNIGHTS_AXE", 4302);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ROYAL_CLERIC_STUFF", 4303);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ROYAL_MAGICIAN_WAND", 4304);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ROYAL_FOXTAIL", 4305);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ROYAL_KATAR", 4306);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ROYAL_MAGICIAN_DAGGER", 4307);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ROYAL_KNUCKLE", 4308);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GUARDIAN_ALCHEMIC_STUFF", 4309);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GUARDIAN_KNIGHTS_ARCHER_BOW", 4310);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ROYAL_WHIP", 4311);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ROYAL_CELLO", 4312);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ROYAL_SAGE_BOOK", 4313);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_TATSUINUNO_UDEWA", 4314);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SANGAKU_HELMET", 4316);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SEIGINO_KANMURI", 4317);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SHIROKISHINO_MANT", 4318);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_MAGMA_SUIT", 4319);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_MAGMA_SUIT", 4320);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_MAGMA_SUIT", 4321);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_TENCHI_SUIT", 4322);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_TENCHI_SUIT", 4323);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_TENCHI_SUIT", 4324);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_ARTIS_SUIT", 4325);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_ARTIS_SUIT", 4326);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_ARTIS_SUIT", 4327);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_MENUS_SUIT", 4328);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_MENUS_SUIT", 4329);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_MENUS_SUIT", 4330);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_HOLY_ROBE", 4331);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_HOLY_ROBE", 4332);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_HOLY_ROBE", 4333);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KYOZYUNO_MINIGLASS", 4334);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_BUKUBUKU_HUNTING_GOOGLE", 4335);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_METAL_PICK", 4336);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_KONO_HOKAN", 4340);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_MAZYUNO_MAIL", 4341);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_MAZYUNO_BOOTS", 4342);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_MAZYUNO_MANT", 4343);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_MAZYUNO_YUBIWA", 4349);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_KONO_SOZIN", 4353);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SAITANNO_ASAME", 4354);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_EIKOWO_TATAESHI_OKEN", 4355);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_HAMETSUWO_MATOISHI_GOKEN", 4356);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MAKARINO_KUTSU", 4358);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GOYUMUSONO_MIKOSHI", 4359);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_OMEGA_CORE", 4364);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_LORD_OF_ROYALS", 4366);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_DEMONS_FAMILIA", 4367);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_RAINSTORM_SUIT", 4369);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_RAINSTORM_SUIT", 4370);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_RAINSTORM_SUIT", 4371);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_PSYCHIC_ROBE", 4375);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_PSYCHIC_ROBE", 4376);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_PSYCHIC_ROBE", 4377);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_SCULL_ROBE", 4379);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_SCULL_ROBE", 4380);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_SCULL_ROBE", 4381);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_RING_OF_CERYNEIA", 4382);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_PARACELSUS_GLOVE", 4384);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NORTHERN_CROSS", 4386);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_SHINO_INDOSHA", 4387);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_ZEPHYROS", 4388);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_BRYIONAK", 4389);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_TSUMETAI_TSURARANO_KATAR", 4390);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_ELECHI_GUITAR", 4391);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_DENKI_UNAGI", 4392);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_MORRIGANNO_HELM", 4393);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_SHAPINIHA_UMINO_SAKEBI", 4394);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_SAINT_ROBE", 4395);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_MAIL", 4396);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_MORRIGANNO_MANT", 4397);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_MORRIGANNO_BELT", 4398);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_MORRIGANNO_PENDANT", 4399);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_PREMIUM_MELON_HEADPHONE", 4401);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KIGURUMI_BEARDOLL", 4403);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_DAGGER", 4404);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_BLADE", 4405);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_CRAYMORE", 4406);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_SPEAR", 4407);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_RANCE", 4408);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_AXE", 4409);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_TWOHAND_AXE", 4410);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_MACE", 4411);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_WAND", 4412);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_STUFF", 4413);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_WING", 4414);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_KATAR", 4415);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_BOOK", 4416);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_CRAW", 4417);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_VIOLIN", 4418);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_WHIP", 4419);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_FUMA_SHURIKEN", 4420);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_HANDGUN", 4421);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_RIFLE", 4422);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_GATLINGGUN", 4423);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_SHOTGUN", 4424);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_GRENADEGUN", 4425);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MELON_FOXTAIL", 4426);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KIRAKIRA_NYANNYAN_CHOKER", 4427);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_OKEANOSNO_KAGO", 4429);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ANTIQUE_GATLINGGUN", 4431);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_CONFIDENCIAL_MAIL", 4432);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_CONFIDENCIAL_MAIL", 4433);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_CONFIDENCIAL_MAIL", 4434);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_PUNISHMENT_ROBE", 4435);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_PUNISHMENT_ROBE", 4436);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_PUNISHMENT_ROBE", 4437);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_CULTIVATION_COAT", 4438);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IMPERIAL_CULTIVATION_COAT", 4439);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GRACE_CULTIVATION_COAT", 4440);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ANCIENT_MEGALIS_MANT", 4443);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_POWERED_INCOME", 4444);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_AVARECO", 4445);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_FAFNIR_HELM", 4446);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_AKAI_NEKOMIMI_MAZYO_BOSHI", 4447);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NIRONO_RIBBON", 4448);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SHUKUSEINO_KUTSU", 4449);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MADOSHINO_KIOKU", 4450);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SHIELD_OF_PHOENIX", 4451);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAIKYONO_SAKURA", 4452);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_WOLF_OFFICER_HAT", 4453);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SPUNTA_MAINYU", 4454);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MOFUMOFU_LOVELY_FOX", 4455);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_RIKUTO_SANRYAKU", 4456);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_FULL_FORCE", 4457);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_ORCLORDNO_YOROI", 4461);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_YAGIGENO_MUFFLER", 4464);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_HOROW_SHOES", 4465);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_FACE_OF_YGGDRASILL", 4485);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_AKURYONO_UMEKIGOE", 4486);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_AEGIS_SYSTEM", 4492);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GUARDIAN_HELM", 4493);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_EINHERJERNO_GAITO", 4502);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_PARACELSUS_COAT", 4503);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MILITARY_GLOVE", 4504);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SEKAIWO_MUSHIBAMU_ZYUSO", 4506);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAIRYOGATA_POWERED_SUIT", 4510);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ONRYO_KAIINO_MIMI", 4511);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MOKOFUWA_SHARK_PAJAMA", 4513);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_TRAVELER_RING", 4514);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_DARK_TRIAD", 4516);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_FURUBITA_MESAI_SCARF", 4517);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NOBLESSE_OBLIGE", 4518);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAGAYAKU_HAKUGINNO_YARI", 4534);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SHINKAI_SEIBUTSUNO_MANT", 4535);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_HAKOBORESHITA_KODACHI", 4536);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SHINREINO_KODACHI", 4537);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_OKINA_TEKKYU", 4538);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KISHINNO_TEKKYU", 4539);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_FURUI_SANNSA_YARI", 4540);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_AKAKI_MOSHONO_YARI", 4541);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAREKINO_TSUE", 4542);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GOSHINBOKUNO_TSUE", 4543);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SABITA_SHOZYU", 4544);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_AR_89I", 4545);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SABITA_SHOTGUN", 4546);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_M_3700", 4547);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GENZYUNO_MIMI", 4548);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MEMENTO_MORI", 4549);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GUARDIAN_CLOTH", 4551);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_EXCALIBUR", 4552);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_GERADRIA", 4553);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_DOOM_SLAYER", 4554);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_IBARANO_TSUE", 4555);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_STUFF_OF_TEAR", 4556);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_ANCIENT_DUGGER", 4557);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_SPRINT_MAIL", 4558);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_GUARD", 4559);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_SILVER_GUARD", 4560);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_SPRINT_SHOES", 4561);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_SPRINT_RING", 4563);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ILLUSION_SPRINT_GLOVE", 4566);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ASMODEUSNO_TSUBASA", 4570);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GORGONNO_HANAKANMURI", 4572);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ARAMAZDNO_TENKE", 4574);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_TWIN_HEAD_DRAGON_MAIL", 4576);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_POKAPOKA_TANPOPO_CAPE", 4577);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_LEGACY_OF_WISE_ONE", 4578);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MAGIC_CELESTIAL_GLOBE", 4579);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_YESTERDAY_ONCE_MORE", 4581);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_CHROM_METAL_PLATE", 4583);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_TENMANO_KUTSU", 4584);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_VALKYRIE_CURSE_BRIGHT", 4585);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KISHINNO_MEIYU", 4588);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_REQUIESCAT_IN_PACE", 4589);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_TYRANT_OF_ERATH", 4591);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_IKOKUNO_DENTO_BOSHI", 4592);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_FURUBITA_SHIHAISHANO_ROBE", 4595);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SHIHAISHANO_ROBE", 4596);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_KAKUSE_SHIHAISHANO_ROBE", 4599);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_LAFINE_STUFF_S2", 41329);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_WANDER_EGG_BASKET_S1", 44235);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_CRYSTAL_BLADE_NECKLACE_S1", 44240);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SHITSUBONO_SHINENTAI_SHOES_S1", 44253);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_BOSONO_SHINENTAI_SHOES_S1", 44259);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_TAIKYOKUNO_MIMIKAZARI_KIIRO_S1", 44285);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_OMEGA_CORE_S1", 44364);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_DEMONS_FAMILIA_S1", 44367);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_PREMIUM_MELON_HEADPHONE_S1", 44401);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_POWERED_INCOME_S1", 44444);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_NIRONO_RIBBON_S1", 44448);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_SHUKUSEINO_KUTSU_S1", 44449);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MOFUMOFU_LOVELY_FOX_S1", 44455);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GUARDIAN_HELM_S1", 44493);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ONRYO_KAIINO_MIMI_S1", 44511);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GENZYUNO_MIMI_S1", 44548);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_ASMODEUSNO_TSUBASA_S1", 44570);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_GORGONNO_HANAKANMURI_S1", 44572);
	g_constDataManager.itemDataManager.RegisterId("MIG_ITEM_ID_MAGIC_CELESTIAL_GLOBE_S1", 44579);



})();



}		// _DATA_CREATE_MODE