name: Deploy to Staging

# 手動で指定された時のみ実行
on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'PR Number to deploy'
        required: true
        type: number # 数値であることを明示

jobs:
  build_and_deploy:
    if: ${{ github.repository == 'roratorio-hub/ratorio' }}
    environment: approval-required-workflow # レビューされるまで最大 30 日保留する
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/pull/${{ github.event.inputs.pull_request_number }}/head

      # --------- ここからメインのワークフロー ----------
      # Node.js のセットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # memo: version 22 のEOLは 2027年4月頃

      # Node.js のパッケージマネージャー pnpm をインストール
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Node.js 依存関係をpnpmでインストール & webpack でビルド
      - name: Install and build Node.js dependencies
        working-directory: workspace
        run: |
             pnpm install --frozen-lockfile
             pnpm run build
             pnpm dlx ts-node --project tsconfig.node.json utils/yamlMergeAndCompress.ts
      # ------------ ここまでメインのワークフロー ----------

      # ワークフローがキックされた日時を json に書き出す
      - name: Get and format current date in JST
        id: get_formatted_date
        working-directory: workspace
        run: |
          JST_DATE=$(TZ="Asia/Tokyo" date +"%Y-%m-%d %H:%M")
          echo "{\"release_date\": \"$JST_DATE\"}" > ../roro/date.json

      - name: Deploy to Staging Repository
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # PR ブランチの内容を一時作業ディレクトリに移動する
          mkdir temp_dist
          mv ./lib temp_dist/
          mv ./jquery temp_dist/
          mv ./ro4 temp_dist/
          mv ./roro temp_dist/
          mv ./dist temp_dist/
          mv ./README.md temp_dist/
          mv ./LICENSE temp_dist/
          mv ./index.html temp_dist/

          # アカウント設定
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # staging リポジトリをクローン
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/roratorio-hub/staging.git staging-repo
          cd staging-repo

          # staging リポジトリの既存ファイルをすべて削除し、一時作業ディレクトリの内容をコピーする
          rm -rf *
          mv ../temp_dist/* .

          # staging リポジトリを更新する
          git add .
          git commit -m "staging request" || true
          git push origin main

      - name: Result
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.inputs.pull_request_number;
            const stagingRepoUrl = 'https://roratorio-hub.github.io/staging';
            const stagingSourceUrl = 'https://github.com/roratorio-hub/staging';
            const previewUrl = `${stagingRepoUrl}/ro4/m/calcx.html`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `🚀 [PRプレビュー環境](${previewUrl})がデプロイされました！５分ほど待ってから確認してください.\nステージング環境の[ソースはこちら](${stagingSourceUrl})`
            });
